services:
  repo:
    image: repocli
    build:
      dockerfile: Dockerfile.arch
    environment:
      - TERM=xterm-256color
    tty: true
    stdin_open: true
    command: bash -c "sleep infinity"
    working_dir: /home/user
    volumes:
      - .:/tmp/repo
