services:
  arch:
    build:
      dockerfile: Dockerfile.arch
    environment:
      - TERM=xterm-256color
    stdin_open: true
    tty: true
    working_dir: /home/user
    command: bash -c "sleep infinity"
    volumes:
      - .:/home/user/.repocli
